# frozen_string_literal: true

require "test_helper"

class XlsxrbAdaptersRubyXLComparisonTest < Test::Unit::TestCase
  def test_side_by_side_cell_operations
    # Create side-by-side workbooks
    orig_wb = ::RubyXL::Workbook.new
    orig_ws = orig_wb[0]

    adapt_wb = ::Xlsxrb::Adapters::RubyXL::Workbook.new
    adapt_ws = adapt_wb[0]

    assert_equal orig_ws.sheet_name, adapt_ws.sheet_name

    # Add various types
    orig_c1 = orig_ws.add_cell(0, 0, "Hello World")
    adapt_c1 = adapt_ws.add_cell(0, 0, "Hello World")
    assert_equal orig_c1.value, adapt_c1.value
    assert_equal orig_c1.raw_value, adapt_c1.raw_value

    orig_c2 = orig_ws.add_cell(0, 1, 12_345)
    adapt_c2 = adapt_ws.add_cell(0, 1, 12_345)
    assert_equal orig_c2.value, adapt_c2.value
    assert_equal orig_c2.raw_value.to_s, adapt_c2.raw_value.to_s

    orig_c3 = orig_ws.add_cell(1, 0, "", "SUM(A1:B1)")
    adapt_c3 = adapt_ws.add_cell(1, 0, "", "SUM(A1:B1)")
    assert_equal orig_c3.formula.expression, adapt_c3.formula.expression

    # Modify cell with change_contents
    orig_c1.change_contents("Modified")
    adapt_c1.change_contents("Modified")
    assert_equal orig_c1.value, adapt_c1.value
    assert_equal orig_c1.raw_value, adapt_c1.raw_value
  end

  def test_interoperability_adapter_write_and_rubyxl_read
    with_tempfile do |filepath|
      adapter_wb = ::Xlsxrb::Adapters::RubyXL::Workbook.new
      adapter_ws = adapter_wb[0]
      adapter_ws.sheet_name = "InterOpSheet"
      adapter_ws.add_cell(0, 0, "RubyXL Compat")
      adapter_ws.add_cell(0, 1, 42)
      adapter_ws.add_cell(1, 0, 100, "SUM(B1:B2)")
      adapter_wb.write(filepath)

      # Read the file generated by xlsxrb adapter using official rubyXL
      official_wb = ::RubyXL::Parser.parse(filepath)
      assert_equal 1, official_wb.worksheets.size
      official_ws = official_wb["InterOpSheet"]
      refute_nil official_ws

      assert_equal "RubyXL Compat", official_ws[0][0].value
      assert_equal 42, official_ws[0][1].value
      assert_equal "SUM(B1:B2)", official_ws[1][0].formula.expression
    end
  end

  def test_interoperability_rubyxl_write_and_adapter_read
    with_tempfile do |filepath|
      official_wb = ::RubyXL::Workbook.new
      official_ws = official_wb[0]
      official_ws.sheet_name = "OfficialSheet"
      official_ws.add_cell(0, 0, "From Official")
      official_ws.add_cell(0, 1, 999)
      official_ws.add_cell(1, 0, 20, "AVERAGE(A1:A5)")
      official_wb.write(filepath)

      # Read the file generated by official rubyXL using xlsxrb adapter
      adapter_wb = ::Xlsxrb::Adapters::RubyXL::Parser.parse(filepath)
      assert_equal 1, adapter_wb.worksheets.size
      adapter_ws = adapter_wb["OfficialSheet"]
      refute_nil adapter_ws

      assert_equal "From Official", adapter_ws[0][0].value
      assert_equal 999, adapter_ws[0][1].value
      assert_equal "AVERAGE(A1:A5)", adapter_ws[1][0].formula.expression
    end
  end

  def test_side_by_side_stream_parsing
    # Generate an XLSX file using rubyXL
    official_wb = ::RubyXL::Workbook.new
    ws = official_wb[0]
    ws.sheet_name = "StreamTest"
    ws.add_cell(0, 0, "Alpha")
    ws.add_cell(0, 1, "Beta")
    ws.add_cell(1, 0, 10)
    ws.add_cell(1, 1, 20)

    stream = official_wb.stream

    # Parse stream with official rubyXL
    stream_for_official = StringIO.new(stream.string)
    parsed_official = ::RubyXL::Parser.parse_buffer(stream_for_official)

    # Parse stream with xlsxrb adapter
    stream_for_adapter = StringIO.new(stream.string)
    parsed_adapter = ::Xlsxrb::Adapters::RubyXL::Parser.parse_buffer(stream_for_adapter)

    # Assert parallel equivalence
    assert_equal parsed_official.worksheets.size, parsed_adapter.worksheets.size
    assert_equal parsed_official[0].sheet_name, parsed_adapter[0].sheet_name

    (0..1).each do |r|
      (0..1).each do |c|
        assert_equal parsed_official[0][r][c].value, parsed_adapter[0][r][c].value
      end
    end
  end

  def test_side_by_side_row_column_manipulation
    orig_wb = ::RubyXL::Workbook.new
    orig_ws = orig_wb[0]
    adapt_wb = ::Xlsxrb::Adapters::RubyXL::Workbook.new
    adapt_ws = adapt_wb[0]

    # Populate 3x3 grid
    3.times do |r|
      3.times do |c|
        orig_ws.add_cell(r, c, "R#{r}C#{c}")
        adapt_ws.add_cell(r, c, "R#{r}C#{c}")
      end
    end

    # Insert row at 1
    orig_ws.insert_row(1)
    adapt_ws.insert_row(1)

    # Insert column at 1
    orig_ws.insert_column(1)
    adapt_ws.insert_column(1)

    # Compare dimensions and values
    assert_equal orig_ws.sheet_data.size, adapt_ws.sheet_data.size
    (0..3).each do |r|
      (0..3).each do |c|
        orig_val = orig_ws[r]&.[](c)&.value
        adapt_val = adapt_ws[r]&.[](c)&.value
        assert_equal orig_val, adapt_val, "Mismatch at (#{r}, #{c})"
      end
    end

    # Delete column at 1
    orig_ws.delete_column(1)
    adapt_ws.delete_column(1)

    # Delete row at 1
    orig_ws.delete_row(1)
    adapt_ws.delete_row(1)

    (0..2).each do |r|
      (0..2).each do |c|
        assert_equal orig_ws[r][c].value, adapt_ws[r][c].value
        assert_equal "R#{r}C#{c}", adapt_ws[r][c].value
      end
    end
  end

  def test_interoperability_styles_adapter_write_and_rubyxl_read
    with_tempfile do |filepath|
      adapter_wb = ::Xlsxrb::Adapters::RubyXL::Workbook.new
      adapter_ws = adapter_wb[0]
      c = adapter_ws.add_cell(0, 0, "Styled Text")
      c.change_font_name("Arial")
      c.change_font_size(14)
      c.change_font_bold(true)
      c.change_font_italics(true)
      c.change_font_color("FF0000")
      c.change_fill("00FF00")
      c.change_horizontal_alignment("center")
      adapter_wb.write(filepath)

      # Read back with official rubyXL
      official_wb = ::RubyXL::Parser.parse(filepath)
      official_cell = official_wb[0][0][0]

      assert_equal "Styled Text", official_cell.value
      assert_equal "Arial", official_cell.font_name
      assert_equal 14, official_cell.font_size
      assert_equal true, official_cell.is_bolded
      assert_equal true, official_cell.is_italicized
    end
  end

  def test_interoperability_merged_cells_adapter_write_and_rubyxl_read
    with_tempfile do |filepath|
      adapter_wb = ::Xlsxrb::Adapters::RubyXL::Workbook.new
      adapter_ws = adapter_wb[0]
      adapter_ws.add_cell(0, 0, "TopLeft")
      adapter_ws.merge_cells(0, 0, 2, 2)
      adapter_wb.write(filepath)

      official_wb = ::RubyXL::Parser.parse(filepath)
      official_ws = official_wb[0]
      assert_equal "TopLeft", official_ws[0][0].value

      merged = official_ws.merged_cells
      refute_empty merged
      assert(merged.any? { |m| (m.is_a?(String) ? m : m.ref.to_s) == "A1:C3" })
    end
  end
end
